### ISSUE TITLE
Add section to join meeting using invite link

### ISSUE THREAD

**Issue by prasantgupta52** [ashavijit/Meetify#16]
### Is your feature request related to a problem? Please describe.

To add the page in the join meeting section of the application where user will input the invite link and join from there

### Describe the solution you'd like

add a page to join meeting

### Describe alternatives you've considered

NA

**Comment by ashavijit** [comment]
@tokyo3001 assigned. You can work on it

**Comment by ashavijit** [comment]
@prasantgupta52 assigned . You can work on it

**Comment by prasantgupta52** [comment]
Created a pull request referring to this issue

**Comment by ashavijit** [comment]
@prasantgupta52 merged
