### ISSUE TITLE
automate commit flow with husky to fix eslint/prettier warning before commiting

### ISSUE THREAD

**Issue by technophile-04** [ashavijit/Meetify#32]
### Is your feature request related to a problem? Please describe.

If you someone don't have prettier installed in vscode, the unformatted code gets committed. 

### Describe the solution you'd like

Adding husky will automate this and will run lint:fix to fix all formatting as well as auto-fixable issue before you commit :)

### Describe alternatives you've considered

Husky, lint-staged

**Comment by ashavijit** [comment]
@technophile-04 nice idea!!

**Comment by technophile-04** [comment]
Will work on this 🙌
